"""add feedback record

Revision ID: 6018b47e3d42
Revises: 75074867de86
Create Date: 2026-09-09 02:00:32.906348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6018b47e3d42'
down_revision: Union[str, None] = '75074867de86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_encounter_id', sa.Uuid(), nullable=False),
    sa.Column('commitment_id', sa.Uuid(), nullable=False),
    sa.Column('match_result', sa.Enum('match', 'partial_match', 'mismatch', name='matchresult', native_enum=False), nullable=False),
    sa.Column('revealed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_encounter_id'], ['case_encounter.id'], ),
    sa.ForeignKeyConstraint(['commitment_id'], ['commitment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_encounter_id')
    )
    op.create_index(op.f('ix_feedback_record_commitment_id'), 'feedback_record', ['commitment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_record_commitment_id'), table_name='feedback_record')
    op.drop_table('feedback_record')
    # ### end Alembic commands ###
