"""add session intake

Revision ID: d1e24e4524ba
Revises: 6018b47e3d42
Create Date: 2026-09-10 11:04:08.020429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e24e4524ba'
down_revision: Union[str, None] = '6018b47e3d42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_intake',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('diagnostic_answers', sa.JSON(), nullable=False),
    sa.Column('diagnostic_score', sa.Integer(), nullable=False),
    sa.Column('primer_shown', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comprehension_answer', sa.String(), nullable=True),
    sa.Column('scaffolding_depth', sa.Enum('high', 'standard', 'low', name='scaffoldingdepth', native_enum=False), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_intake')
    # ### end Alembic commands ###
