"""add contrast entry

Revision ID: 2a91afc216ff
Revises: d1e24e4524ba
Create Date: 2026-09-11 16:11:21.012831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a91afc216ff'
down_revision: Union[str, None] = 'd1e24e4524ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contrast_entry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_encounter_id', sa.Uuid(), nullable=False),
    sa.Column('contrast_type', sa.Enum('twin_counter_case', 'open_area', name='contrasttype', native_enum=False), nullable=False),
    sa.Column('counter_case_id', sa.Uuid(), nullable=True),
    sa.Column('learner_response', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_encounter_id'], ['case_encounter.id'], ),
    sa.ForeignKeyConstraint(['counter_case_id'], ['case.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_encounter_id')
    )
    op.create_index(op.f('ix_contrast_entry_counter_case_id'), 'contrast_entry', ['counter_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contrast_entry_counter_case_id'), table_name='contrast_entry')
    op.drop_table('contrast_entry')
    # ### end Alembic commands ###
