"""add user, auth_identity, and learning_identity tables

Revision ID: e97db85c3a70
Revises: f527b60e072a
Create Date: 2026-09-15 21:56:01.669341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e97db85c3a70'
down_revision: Union[str, None] = 'f527b60e072a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Two hand-adjustments from the raw autogenerate output:
    # 1. sqlmodel.sql.sqltypes.AutoString() had no corresponding import in
    #    the generated file (would NameError on a real run) -- replaced
    #    with sa.String(), matching every other migration's own style.
    # 2. autogenerate also proposed dropping and recreating
    #    ck_comparison_set_case_inclusion_reason (from the InclusionReason
    #    migration, f527b60e072a) as a false positive: its own comparator
    #    disagreed with itself about the constraint's literal text, but
    #    the live definition matches what downgrade() below would recreate
    #    verbatim (verified directly against the real dev database).
    #    Removed -- this migration only adds the three new tables.
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('active', name='userstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_identity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('google', name='authprovider', native_enum=False), nullable=False),
    sa.Column('provider_subject', sa.String(), nullable=False),
    sa.Column('verified_email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_subject', name='uq_auth_identity_provider_subject')
    )
    op.create_index(op.f('ix_auth_identity_user_id'), 'auth_identity', ['user_id'], unique=False)
    op.create_table('learning_identity',
    sa.Column('learner_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('learner_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_identity')
    op.drop_index(op.f('ix_auth_identity_user_id'), table_name='auth_identity')
    op.drop_table('auth_identity')
    op.drop_table('user')
    # ### end Alembic commands ###
