"""add_technology_intake_gate_posture_and_set_contrast_entry

Revision ID: d212d050cd65
Revises: 7cc497198726
Create Date: 2026-09-13 15:41:03.975144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd212d050cd65'
down_revision: Union[str, None] = '7cc497198726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('set_contrast_entry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('contrast_type', sa.Enum('twin_counter_case', 'open_area', name='contrasttype', native_enum=False), nullable=False),
    sa.Column('learner_response', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.add_column('technology_intake', sa.Column('gate', sa.Enum('G1', 'G2', 'G3', 'G4', 'G5', 'G6', name='gate', native_enum=False), nullable=True))
    op.add_column('technology_intake', sa.Column('posture_response', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technology_intake', 'posture_response')
    op.drop_column('technology_intake', 'gate')
    op.drop_table('set_contrast_entry')
    # ### end Alembic commands ###
