"""add_comparison_set_case_sequence_no

Revision ID: 7cc497198726
Revises: b7e89cbec3d1
Create Date: 2026-09-13 15:22:05.925031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cc497198726'
down_revision: Union[str, None] = 'b7e89cbec3d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comparison_set_case', sa.Column('sequence_no', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_comparison_set_case_set_sequence', 'comparison_set_case', ['comparison_set_id', 'sequence_no'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_comparison_set_case_set_sequence', 'comparison_set_case', type_='unique')
    op.drop_column('comparison_set_case', 'sequence_no')
    # ### end Alembic commands ###
