"""add case, session, encounter and commitment models

Revision ID: 75074867de86
Revises: 0001_initial
Create Date: 2026-09-08 19:38:24.843223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75074867de86'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('case_type', sa.Enum('harm', 'counter_case', name='casetype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('draft', 'reviewed', 'published', name='casestatus', native_enum=False), nullable=False),
    sa.Column('narrative_until_crossroads', sa.String(), nullable=False),
    sa.Column('full_narrative', sa.String(), nullable=False),
    sa.Column('main_path_pattern', sa.Enum('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', name='pattern', native_enum=False), nullable=False),
    sa.Column('main_path_gate', sa.Enum('G1', 'G2', 'G3', 'G4', 'G5', 'G6', name='gate', native_enum=False), nullable=False),
    sa.Column('source_references', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_area'), 'case', ['area'], unique=False)
    op.create_index(op.f('ix_case_status'), 'case', ['status'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('route', sa.Enum('student', 'researcher', name='sessionroute', native_enum=False), nullable=False),
    sa.Column('mode', sa.Enum('individual', 'group', 'lecture', name='sessionmode', native_enum=False), nullable=False),
    sa.Column('learner_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_learner_id'), 'session', ['learner_id'], unique=False)
    op.create_table('case_encounter',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('sequence_no >= 1 AND sequence_no <= 3', name='ck_case_encounter_sequence_no_range'),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'sequence_no', name='uq_case_encounter_session_sequence')
    )
    op.create_index(op.f('ix_case_encounter_case_id'), 'case_encounter', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_encounter_session_id'), 'case_encounter', ['session_id'], unique=False)
    op.create_table('case_tagged_gate',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('gate', sa.Enum('G1', 'G2', 'G3', 'G4', 'G5', 'G6', name='gate', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.PrimaryKeyConstraint('case_id', 'gate')
    )
    op.create_table('case_tagged_pattern',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('pattern', sa.Enum('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', name='pattern', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.PrimaryKeyConstraint('case_id', 'pattern')
    )
    op.create_table('counter_case_link',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('harm_case_id', sa.Uuid(), nullable=False),
    sa.Column('counter_case_id', sa.Uuid(), nullable=False),
    sa.Column('responsibility_posture_contrast', sa.String(), nullable=False),
    sa.Column('gate_lever', sa.Enum('G1', 'G2', 'G3', 'G4', 'G5', 'G6', name='gate', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['counter_case_id'], ['case.id'], ),
    sa.ForeignKeyConstraint(['harm_case_id'], ['case.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('counter_case_id')
    )
    op.create_index(op.f('ix_counter_case_link_harm_case_id'), 'counter_case_link', ['harm_case_id'], unique=False)
    op.create_table('commitment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_encounter_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pattern', sa.Enum('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', name='pattern', native_enum=False), nullable=False),
    sa.Column('gate', sa.Enum('G1', 'G2', 'G3', 'G4', 'G5', 'G6', name='gate', native_enum=False), nullable=False),
    sa.Column('framing_answers', sa.JSON(), nullable=False),
    sa.CheckConstraint('sequence_no >= 1', name='ck_commitment_sequence_no_positive'),
    sa.ForeignKeyConstraint(['case_encounter_id'], ['case_encounter.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_encounter_id', 'sequence_no', name='uq_commitment_encounter_sequence')
    )
    op.create_index(op.f('ix_commitment_case_encounter_id'), 'commitment', ['case_encounter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commitment_case_encounter_id'), table_name='commitment')
    op.drop_table('commitment')
    op.drop_index(op.f('ix_counter_case_link_harm_case_id'), table_name='counter_case_link')
    op.drop_table('counter_case_link')
    op.drop_table('case_tagged_pattern')
    op.drop_table('case_tagged_gate')
    op.drop_index(op.f('ix_case_encounter_session_id'), table_name='case_encounter')
    op.drop_index(op.f('ix_case_encounter_case_id'), table_name='case_encounter')
    op.drop_table('case_encounter')
    op.drop_index(op.f('ix_session_learner_id'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_case_status'), table_name='case')
    op.drop_index(op.f('ix_case_area'), table_name='case')
    op.drop_table('case')
    # ### end Alembic commands ###
