"""add_researcher_route_models

Revision ID: b7e89cbec3d1
Revises: 2a91afc216ff
Create Date: 2026-09-13 09:08:32.937684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7e89cbec3d1'
down_revision: Union[str, None] = '2a91afc216ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_tagged_function',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('function', sa.Enum('sensing', 'generating', 'controlling', 'predicting', 'editing', 'optimizing', 'fabricating', 'computing', name='function', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.PrimaryKeyConstraint('case_id', 'function')
    )
    op.create_table('comparison_set',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('functions', sa.JSON(), nullable=False),
    sa.Column('was_widened', sa.Boolean(), nullable=False),
    sa.Column('case_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('researcher_prediction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.Enum('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', name='pattern', native_enum=False), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'pattern', name='uq_researcher_prediction_session_pattern'),
    sa.UniqueConstraint('session_id', 'rank', name='uq_researcher_prediction_session_rank')
    )
    op.create_index(op.f('ix_researcher_prediction_session_id'), 'researcher_prediction', ['session_id'], unique=False)
    op.create_table('technology_intake',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('raw_description', sa.String(), nullable=False),
    sa.Column('domain', sa.Enum('Material Science', 'Advanced Manufacturing / 3D Printing', 'Semiconductors and Nanotechnology', 'Artificial Intelligence', 'Cyber Technologies', 'Quantum Technology', 'Robotics & Autonomous Systems', 'Neurotechnology', 'Biochemistry', name='domain', native_enum=False), nullable=True),
    sa.Column('functions', sa.JSON(), nullable=True),
    sa.Column('forms', sa.JSON(), nullable=True),
    sa.Column('mapping_status', sa.Enum('mapped', 'partial', 'unmapped', name='mappingstatus', native_enum=False), nullable=False),
    sa.Column('clarification_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('comparison_set_case',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('comparison_set_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('inclusion_reason', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.ForeignKeyConstraint(['comparison_set_id'], ['comparison_set.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comparison_set_id', 'case_id', name='uq_comparison_set_case_set_case')
    )
    op.create_index(op.f('ix_comparison_set_case_case_id'), 'comparison_set_case', ['case_id'], unique=False)
    op.create_index(op.f('ix_comparison_set_case_comparison_set_id'), 'comparison_set_case', ['comparison_set_id'], unique=False)
    op.add_column('case', sa.Column('domain', sa.Enum('Material Science', 'Advanced Manufacturing / 3D Printing', 'Semiconductors and Nanotechnology', 'Artificial Intelligence', 'Cyber Technologies', 'Quantum Technology', 'Robotics & Autonomous Systems', 'Neurotechnology', 'Biochemistry', name='domain', native_enum=False), nullable=False))
    op.add_column('case', sa.Column('forms', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case', 'forms')
    op.drop_column('case', 'domain')
    op.drop_index(op.f('ix_comparison_set_case_comparison_set_id'), table_name='comparison_set_case')
    op.drop_index(op.f('ix_comparison_set_case_case_id'), table_name='comparison_set_case')
    op.drop_table('comparison_set_case')
    op.drop_table('technology_intake')
    op.drop_index(op.f('ix_researcher_prediction_session_id'), table_name='researcher_prediction')
    op.drop_table('researcher_prediction')
    op.drop_table('comparison_set')
    op.drop_table('case_tagged_function')
    # ### end Alembic commands ###
